Schema.voices.Add("Human", "ALMOST MADE SENSE", "That... almost made sense.", {"vo/npc/male01/vanswer09.wav", "vo/npc/female01/vanswer09.wav"})
Schema.voices.Add("Human", "ATE SOMETHING BAD", "I think I ate something bad.", {"vo/npc/male01/question27.wav", "vo/npc/female01/question27.wav"})
Schema.voices.Add("Human", "ANTIQUES", "Jeez! That place was full of antiques!", {"vo/outland_12/reb1_buildingexplo04.wav", "common/null.wav"})
Schema.voices.Add("Human", "AGH", "Aaaaaaagh!", {"vo/outland_12/reb1_sawmillexplo05.wav", "common/null.wav"})
Schema.voices.Add("Human", "BARE FISTS", "One time, back in the city, I saw a guy take down a Hunter with his bare fists.", {"vo/outland_12/reb1_huntprompt05.wav", "common/null.wav"})
Schema.voices.Add("Human", "BEHIND YOU", "Behind you!", {"vo/npc/male01/behindyou01.wav", "vo/npc/female01/behindyou01.wav"})
Schema.voices.Add("Human", "BAD MEMORY", "Someday, this will all be a bad memory.", {"vo/npc/male01/question20.wav", "vo/npc/female01/question20.wav"})
Schema.voices.Add("Human", "BETTING MAN", "I'm not a betting man... but the odds are not good.", {"vo/npc/male01/question21.wav", "vo/npc/female01/question21.wav"})
Schema.voices.Add("Human", "BETTER MYSELF", "Couldn't have put it better myself.", {"vo/npc/male01/vanswer08.wav", "vo/npc/female01/vanswer08.wav"})
Schema.voices.Add("Human", "BULLSHIT", "This is bullshit!", {"vo/npc/male01/question26.wav", "vo/npc/female01/question26.wav"})
Schema.voices.Add("Human", "CANT HOLD OUT", "We can't hold out much longer!", {"vo/outland_02/griggs_cantholdout.wav", "common/null.wav"})
Schema.voices.Add("Human", "CHANGE IS IN THE AIR", "Finally change is in the air!", {"vo/npc/male01/question16.wav", "vo/npc/female01/question16.wav"})
Schema.voices.Add("Human", "CIVIL PROTECTION", "Civil Protection!", {"vo/npc/male01/civilprotection01.wav", "vo/npc/female01/civilprotection01.wav"})
Schema.voices.Add("Human", "COMBINE", "Combine!", {"vo/npc/male01/combine01.wav", "vo/npc/female01/combine01.wav"})
Schema.voices.Add("Human", "COMBINE BASTARDS", "These Combine bastards just don't give up!", {"vo/outland_12/reb1_lastwaveannounced07.wav", "common/null.wav"})
Schema.voices.Add("Human", "COMING IN HERE", "They're definitely coming in here!", {"vo/trainyard/male01/cit_window_use02.wav", "vo/trainyard/female02/cit_window_use02.wav"})
Schema.voices.Add("Human", "CONCENTRATE ON THE TASK", "L-let's concentrate on the task at hand.", {"vo/npc/male01/answer18.wav", "vo/npc/female01/answer18.wav"})
Schema.voices.Add("Human", "COULDN'T HELP", "I had a feeling even he couldn't help us.", {"vo/npc/male01/gordead_ans09.wav", "vo/npc/female01/gordead_ans09.wav"})
Schema.voices.Add("Human", "CPS", "CP's!", {"vo/npc/male01/cps01.wav", "vo/npc/female01/cps01.wav"})
Schema.voices.Add("Human", "CHEER1", "*Cheering!*", {"vo/coast/odessa/male01/nlo_cheer01.wav", "vo/coast/odessa/female01/nlo_cheer01.wav"})
Schema.voices.Add("Human", "CHEER2", "*Cheering!*", {"vo/coast/odessa/male01/nlo_cheer02.wav", "vo/coast/odessa/female01/nlo_cheer02.wav"})
Schema.voices.Add("Human", "CHEER3", "*Cheering!*", {"vo/coast/odessa/male01/nlo_cheer03.wav", "vo/coast/odessa/female01/nlo_cheer03.wav"})
Schema.voices.Add("Human", "CHEER4", "*Cheering!*", {"vo/coast/odessa/male01/nlo_cheer04.wav"})
Schema.voices.Add("Human", "DARE SAY", "If you dare say - that's gotta hurt - I'll kill you.", {"vo/npc/male01/gordead_ans07.wav", "vo/npc/female01/gordead_ans07.wav"})
Schema.voices.Add("Human", "DECENT MEAL", "I don't know about you, but I'm ready to join Civil Protection just to get a decent meal.", {"vo/trainyard/male01/cit_foodline04.wav", "vo/trainyard/female01/cit_foodline04.wav"})
Schema.voices.Add("Human", "DEJA VU", "Woah, Déjà vu.", {"vo/npc/male01/question05.wav", "vo/npc/female01/question05.wav"})
Schema.voices.Add("Human", "DESERVE THIS", "What did I do to deserve this?", {"vo/npc/male01/vanswer14.wav", "vo/npc/female01/vanswer14.wav"})
Schema.voices.Add("Human", "DO NICELY", "This'll do nicely!", {"vo/npc/male01/thislldonicely01.wav", "vo/npc/female01/thislldonicely01.wav"})
Schema.voices.Add("Human", "DOESN'T LOOK GOOD", "This doesn't look good.", {"vo/trainyard/male01/cit_window_use01.wav", "vo/trainyard/female01/cit_window_use01.wav"})
Schema.voices.Add("Human", "DOING SOMETHING", "Shouldn't we be... doing something?", {"vo/npc/male01/doingsomething.wav", "vo/npc/female01/doingsomething.wav"})
Schema.voices.Add("Human", "DON'T BE SO SURE", "Don't be so sure of that.", {"vo/npc/male01/answer21.wav", "vo/npc/female01/answer21.wav"})
Schema.voices.Add("Human", "DON'T DREAM", "I don't dream anymore.", {"vo/npc/male01/question03.wav", "vo/npc/female01/question03.wav"})
Schema.voices.Add("Human", "DON'T FEEL ANYTHING", "I don't feel anything, anymore.", {"vo/npc/male01/question18.wav", "vo/npc/female01/question18.wav"})
Schema.voices.Add("Human", "DON'T TELL ME", "Don't tell me.", {"vo/npc/male01/gordead_ans03.wav", "vo/npc/female01/gordead_ans03.wav"})
Schema.voices.Add("Human", "DONE FOR", "We're done for!", {"vo/npc/male01/gordead_ans14.wav", "vo/npc/female01/gordead_ans14.wav"})
Schema.voices.Add("Human", "DONE THIS BEFORE", "He's done this before, he'll be okay!", {"vo/npc/male01/gordead_ans18.wav", "vo/npc/female01/gordead_ans18.wav"})
Schema.voices.Add("Human", "DWELL ON IT", "Try not to dwell on it.", {"vo/npc/male01/answer04.wav", "vo/npc/female01/answer04.wav"})
Schema.voices.Add("Human", "END LIKE THIS", "It's not supposed to end like this!", {"vo/npc/male01/gordead_ques14.wav", "vo/npc/female01/gordead_ques14.wav"})
Schema.voices.Add("Human", "ENDED UP WITH YOU", "Sometimes, I wonder how I ended up with you.", {"vo/npc/male01/vquestion04.wav", "vo/npc/female01/vquestion04.wav"})
Schema.voices.Add("Human", "EVERYONE READY", "Everyone ready?", {"vo/outland_12/reb1_prepare_battle_02.wav", "common/null.wav"})
Schema.voices.Add("Human", "EVERYWHERE", "Oh god, they're coming from everywhere!", {"vo/outland_02/griggs_everywhere.wav", "common/null.wav"})
Schema.voices.Add("Human", "EXCUSE ME", "Excuse me.", {"vo/npc/male01/excuseme02.wav", "vo/npc/female01/excuseme02.wav"})
Schema.voices.Add("Human", "FANTASTIC", "Fan-tastic!", {"vo/npc/male01/fantastic01.wav", "vo/npc/female01/fantastic01.wav"})
Schema.voices.Add("Human", "FEEL IT", "Do you feel it? I feel it!", {"vo/npc/male01/question17.wav", "vo/npc/female01/question17.wav"})
Schema.voices.Add("Human", "FIGURES", "Figures.", {"vo/npc/male01/answer03.wav", "vo/npc/female01/answer03.wav"})
Schema.voices.Add("Human", "FINALLY", "Finally!", {"vo/npc/male01/finally.wav", "vo/npc/female01/finally.wav"})
Schema.voices.Add("Human", "FINALLY COME", "I can't believe this day has finally come!", {"vo/npc/male01/question10.wav", "vo/npc/female01/question10.wav"})
Schema.voices.Add("Human", "FIRST TIME", "Wouldn't be the first time.", {"vo/npc/male01/answer36.wav", "vo/npc/female01/answer36.wav"})
Schema.voices.Add("Human", "FIRST TIME FOR EVERYTHING", "There's a first time for everything.", {"vo/npc/male01/answer40.wav", "vo/npc/female01/answer40.wav"})
Schema.voices.Add("Human", "FOLLOWED", "You weren't followed, were ya?", {"vo/outland_02/griggs_followed03.wav", "common/null.wav"})
Schema.voices.Add("Human", "FORGET IT", "Forget it.", {"vo/outland_02/griggs_betweenwave_conver2_03.wav", "common/null.wav"})
Schema.voices.Add("Human", "FREEDOM", "You smell that? It's freedom!", {"vo/npc/male01/question07.wav", "vo/npc/female01/question07.wav"})
Schema.voices.Add("Human", "GOD DAMN IT", "God... damn... it...", {"vo/outland_12/reb1_lastwaveannounced03.wav", "common/null.wav"})
Schema.voices.Add("Human", "GOING SO WELL", "Things were going so well.", {"vo/npc/male01/gordead_ans02.wav", "vo/npc/female01/gordead_ans02.wav"})
Schema.voices.Add("Human", "GONNA BE SICK", "I'm gonna be sick.", {"vo/npc/male01/gordead_ans19.wav", "vo/npc/female01/gordead_ans19.wav"})
Schema.voices.Add("Human", "GET DOWN", "Get down!", {"vo/npc/male01/getdown02.wav", "vo/npc/female01/getdown02.wav"})
Schema.voices.Add("Human", "GET UP", "Get up!", {"vo/episode_1/npc/male01/cit_buddykilled05.wav", "vo/episode_1/npc/female01/cit_buddykilled05.wav"})
Schema.voices.Add("Human", "GET GOING", "Are we gonna get going, soon?", {"vo/npc/male01/getgoingsoon.wav", "vo/npc/female01/getgoingsoon.wav"})
Schema.voices.Add("Human", "GET TO YOU", "Try not to let it get to you.", {"vo/npc/male01/answer35.wav", "vo/npc/female01/answer35.wav"})
Schema.voices.Add("Human", "GET USED TO", "Some things I just... never get used to.", {"vo/npc/male01/vquestion02.wav", "vo/npc/female01/vquestion02.wav"})
Schema.voices.Add("Human", "GO ON", "Go on!", {"vo/canals/male01/stn6_go_nag02.wav", "vo/canals/female01/stn6_go_nag02.wav"})
Schema.voices.Add("Human", "GONNA GET IT", "Oh no, now we're really gonna get it.", {"vo/trainyard/male01/cit_tvbust05.wav", "vo/trainyard/female01/cit_tvbust05.wav"})
Schema.voices.Add("Human", "GONNA MAKE IT", "I'm gonna make it. I /am/ gonna make it.", {"vo/outland_12/reb1_lastwaveannounced05.wav", "common/null.wav"})
Schema.voices.Add("Human", "GONNA MATE", "When this is all over, I'm gonna mate.", {"vo/npc/male01/question29.wav", "vo/npc/female01/question29.wav"})
Schema.voices.Add("Human", "GOOD GOD", "Good God!", {"vo/npc/male01/goodgod.wav", "vo/npc/female01/goodgod.wav"})
Schema.voices.Add("Human", "GOT IT", "You got it!", {"vo/npc/male01/yougotit02.wav", "vo/npc/female01/yougotit02.wav"})
Schema.voices.Add("Human", "GOT ONE", "I got one!", {"vo/npc/male01/gotone02.wav", "vo/npc/female01/gotone02.wav"})
Schema.voices.Add("Human", "GOT THAT FROM ME", "You got that from me!", {"vo/npc/male01/vanswer06.wav", "vo/npc/female01/vanswer06.wav"})
Schema.voices.Add("Human", "GOTTA RELOAD", "Gotta reload!", {"vo/npc/male01/gottareload01.wav", "vo/npc/female01/gottareload01.wav"})
Schema.voices.Add("Human", "GUNS ARENT CUTTING IT", "Our guns aren't cuttin' it!", {"vo/outland_08/chopper/reb1_chop_chopper_hint01.wav", "common/null.wav"})
Schema.voices.Add("Human", "GUNSHIP", "Gunship!", {"vo/npc/male01/gunship02.wav", "vo/npc/female01/gunship02.wav"})
Schema.voices.Add("Human", "GUT", "*Pain* Hit in the gut!", {"vo/npc/male01/hitingut01.wav", "vo/npc/female01/hitingut01.wav"})
Schema.voices.Add("Human", "GUTTER", "Your mind is in the gutter.", {"vo/npc/male01/answer20.wav", "vo/npc/female01/answer20.wav"})
Schema.voices.Add("Human", "HATE THOSE THINGS", "I hate those frickin' things!", {"vo/outland_12/reb2_magblasted09.wav", "common/null.wav"})
Schema.voices.Add("Human", "HAWAII", "Don't forget Hawaii.", {"vo/npc/male01/answer34.wav", "vo/npc/female01/answer34.wav"})
Schema.voices.Add("Human", "HEADCRABS", "Headcrabs!", {"vo/npc/male01/headcrabs01.wav", "vo/npc/female01/headcrabs01.wav"})
Schema.voices.Add("Human", "HEADS UP", "Heads up!", {"vo/npc/male01/headsup02.wav", "vo/npc/female01/headsup02.wav"})
Schema.voices.Add("Human", "HELL OUT", "Get the hell, outta here!", {"vo/npc/male01/gethellout.wav", "vo/npc/female01/gethellout.wav"})
Schema.voices.Add("Human", "HELP YOU", "I'd like to help you, but it's out of the question.", {"vo/trainyard/male01/cit_pedestrian05.wav", "vo/trainyard/female01/cit_pedestrian05.wav"})
Schema.voices.Add("Human", "HE'S DEAD", "He's dead.", {"vo/npc/male01/gordead_ques01.wav", "vo/npc/female01/gordead_ques01.wav"})
Schema.voices.Add("Human", "HEY STAY FOCUSED", "Hey, stay focused! Get to cover and start shooting!", {"vo/outland_12/reb1_prepare_battle_09.wav", "common/null.wav"})
Schema.voices.Add("Human", "HELP2", "Help!", {"vo/npc/male01/help01.wav", "vo/npc/female01/help01.wav"})
Schema.voices.Add("Human", "HERE AMMO", "Here, ammo!", {"vo/npc/male01/ammo03.wav", "vo/npc/female01/ammo03.wav"})
Schema.voices.Add("Human", "TAKE AMMO", "Take some ammo!", {"vo/npc/male01/ammo04.wav", "vo/npc/female01/ammo04.wav"})
Schema.voices.Add("Human", "HERE COME THE HACKS", "Here come the hacks!", {"vo/npc/male01/herecomehacks01.wav", "vo/npc/female01/herecomehacks01.wav"})
Schema.voices.Add("Human", "HERE THEY COME", "Here they come!", {"vo/npc/male01/heretheycome01.wav", "vo/npc/female01/heretheycome01.wav"})
Schema.voices.Add("Human", "HERE WE GO AGAIN", "Oh, man... here we go again.", {"vo/outland_12/reb1_lastwaveannounced02.wav", "common/null.wav"})
Schema.voices.Add("Human", "HI", "Hi.", {"vo/npc/male01/hi01.wav", "vo/npc/female01/hi01.wav"})
Schema.voices.Add("Human", "HOLD AGAINST", "I won't hold it against you.", {"vo/npc/male01/answer02.wav", "vo/npc/female01/answer02.wav"})
Schema.voices.Add("Human", "HOLD EM", "Go on, I'll hold 'em!", {"vo/trainyard/cit_blocker_holdem.wav"})
Schema.voices.Add("Human", "HOLY SHIT", "Holy... shit...", {"vo/outland_12/reb1_sawmillexplo03.wav", "common/null.wav"})
Schema.voices.Add("Human", "HOW ABOUT THAT", "How 'bout that?", {"vo/npc/male01/answer25.wav", "vo/npc/female01/answer25.wav"})
Schema.voices.Add("Human", "HORSE", "I could eat a horse, hooves and all.", {"vo/npc/male01/question09.wav", "vo/npc/female01/question09.wav"})
Schema.voices.Add("Human", "HUNGRY", "God, I'm hungry.", {"vo/npc/male01/question28.wav", "vo/npc/female01/question28.wav"})
Schema.voices.Add("Human", "I'M READY", "Okay, I'm ready.", {"vo/npc/male01/okimready01.wav", "vo/npc/female01/okimready01.wav"})
Schema.voices.Add("Human", "IM BUSY", "Can't you see I'm busy?", {"vo/npc/male01/busy02.wav", "vo/npc/female01/busy02.wav"})
Schema.voices.Add("Human", "IM HURT", "Agh, I'm hurt!", {"vo/npc/male01/imhurt01.wav", "vo/npc/female01/imhurt01.wav"})
Schema.voices.Add("Human", "INCOMING", "Incoming!", {"vo/npc/male01/incoming02.wav", "vo/npc/female01/incoming02.wav"})
Schema.voices.Add("Human", "JUST IN TIME", "You made it just in time. We gotta clear out of here before we're discovered.", {"vo/canals/male01/gunboat_justintime.wav", "vo/canals/female01/gunboat_justintime.wav"})
Schema.voices.Add("Human", "KILLING ME", "Stop, you're killing me.", {"vo/npc/male01/vanswer13.wav", "vo/npc/female01/vanswer13.wav"})
Schema.voices.Add("Human", "KNEW IT WOULD END", "I knew it would end like this!", {"vo/outland_11a/silo/reb1_idles03.wav", "common/null.wav"})
Schema.voices.Add("Human", "KNOW WHAT", "'Know what you mean.", {"vo/npc/male01/answer08.wav", "vo/npc/female01/answer08.wav"})
Schema.voices.Add("Human", "LEAD THE WAY", "You lead the way!", {"vo/npc/male01/leadtheway01.wav", "vo/npc/female01/leadtheway01.wav"})
Schema.voices.Add("Human", "LET US THROUGH", "Let us through!", {"vo/streetwar/barricade/male01/c17_05_letusthru.wav", "vo/streetwar/barricade/female01/c17_05_letusthru.wav"})
Schema.voices.Add("Human", "LEARNED THEIR LESSON", "I think they learned their lesson.", {"vo/outland_11a/silo/mirt_silo_trouble03.wav", "common/null.wav"})
Schema.voices.Add("Human", "LEAVE A MARK", "That's gonna leave a mark.", {"vo/outland_08/chopper/rebc_chop_hit02.wav", "common/null.wav"})
Schema.voices.Add("Human", "LEAVE IT ALONE", "Leave it alone.", {"vo/npc/male01/answer38.wav", "vo/npc/female01/answer38.wav"})
Schema.voices.Add("Human", "LET US OUT", "Let us out of here!.", {"vo/streetwar/nexus/male01/c17_10_letusout.wav", "vo/streetwar/nexus/female01/c17_10_letusout.wav"})
Schema.voices.Add("Human", "LIKE THAT", "Hah, like that?", {"vo/npc/male01/likethat.wav", "vo/npc/female01/likethat.wav"})
Schema.voices.Add("Human", "LITTLE CORNER", "I've got my little corner and I'm sticking to it!", {"vo/npc/male01/littlecorner01.wav", "vo/npc/female01/littlecorner01.wav"})
Schema.voices.Add("Human", "LIVE MY LIFE", "If I could live my life over again...", {"vo/npc/male01/question13.wav", "vo/npc/female01/question13.wav"})
Schema.voices.Add("Human", "LOOK OUT BELOW", "Look out below!", {"vo/npc/male01/cit_dropper04.wav", "vo/npc/female01/cit_dropper04.wav"})
Schema.voices.Add("Human", "LOOK SUSPICIOUS", "Don't sit near me, it'll look suspicious.", {"vo/trainyard/male01/cit_bench03.wav", "vo/trainyard/female01/cit_bench03.wav"})
Schema.voices.Add("Human", "MAN DOWN", "Man down!", {"vo/episode_1/npc/male01/cit_buddykilled08.wav", "vo/episode_1/npc/female01/cit_buddykilled08.wav"})
Schema.voices.Add("Human", "MATTER OF TIME", "It was just a matter of time.", {"vo/trainyard/male01/cit_window_use03.wav", "vo/trainyard/female01/cit_window_use03.wav"})
Schema.voices.Add("Human", "MIND ON YOUR WORK", "Keep your mind on your work!", {"vo/npc/male01/answer19.wav", "vo/npc/female01/answer19.wav"})
Schema.voices.Add("Human", "MISUNDERESTIMATED", "I think we misunderestimated.", {"vo/outland_02/griggs_underest.wav", "common/null.wav"})
Schema.voices.Add("Human", "MOVE ON", "Let's get a move on! We gotta clear out before they target us!", {"vo/canals/male01/gunboat_moveon.wav", "vo/canals/female01/gunboat_moveon.wav"})
Schema.voices.Add("Human", "MOAN1", "Ugh... agh", {"vo/npc/male01/moan01.wav", "vo/npc/female01/moan01.wav"})
Schema.voices.Add("Human", "MOAN2", "Ugh... agh-hgh", {"vo/npc/male01/moan02.wav", "vo/npc/female01/moan02.wav"})
Schema.voices.Add("Human", "MOAN3", "Ugh...", {"vo/npc/male01/moan03.wav", "vo/npc/female01/moan03.wav"})
Schema.voices.Add("Human", "MOAN4", "Oghhh", {"vo/npc/male01/moan04.wav", "vo/npc/female01/moan04.wav"})
Schema.voices.Add("Human", "MOAN5", "Aaagh", {"vo/npc/male01/moan05.wav", "vo/npc/female01/moan05.wav"})
Schema.voices.Add("Human", "MORE INFORMATION", "That's more information than I require.", {"vo/npc/male01/answer26.wav", "vo/npc/female01/answer26.wav"})
Schema.voices.Add("Human", "MUMBO JUMBO", "Enough of your mumbo-jumbo.", {"vo/npc/male01/vanswer01.wav", "vo/npc/female01/vanswer01.wav"})
Schema.voices.Add("Human", "MY ARM", "Gagh, my arm!", {"vo/npc/male01/myarm02.wav", "vo/npc/female01/myarm01.wav"})
Schema.voices.Add("Human", "MY GUT", "Agh, my gut!", {"vo/npc/male01/mygut02.wav", "vo/npc/female01/mygut02.wav"})
Schema.voices.Add("Human", "MY LEG", "Agh, my leg!", {"vo/npc/male01/myleg01.wav", "vo/npc/female01/myleg01.wav"})
Schema.voices.Add("Human", "NEIGHBOURHOOD", "Here goes the rest of the neighbourhood.", {"vo/trainyard/male01/cit_window_use04.wav", "vo/trainyard/female01/cit_window_use04.wav"})
Schema.voices.Add("Human", "NEVER CAN TELL", "Never can tell.", {"vo/npc/male01/answer23.wav", "vo/npc/female01/answer23.wav"})
Schema.voices.Add("Human", "NEVER GOING TO MAKE", "They're never going to make a stalker out of me!", {"vo/npc/male01/question15.wav", "vo/npc/female01/question15.wav"})
Schema.voices.Add("Human", "NEW IN TOWN", "New in town, aren't you?", {"vo/trainyard/male01/cit_pedestrian01.wav", "vo/trainyard/female01/cit_pedestrian01.wav"})
Schema.voices.Add("Human", "NICE", "Nice.", {"vo/npc/male01/nice01.wav", "vo/npc/female01/nice01.wav"})
Schema.voices.Add("Human", "NIP THAT KINDA TALK", "You should nip that kinda talk in the bud.", {"vo/npc/male01/answer31.wav", "vo/npc/female01/answer31.wav"})
Schema.voices.Add("Human", "NOO", "No! Nooo!.", {"vo/coast/odessa/male01/nlo_cubdeath01.wav", "vo/coast/odessa/female01/nlo_cubdeath01.wav"})
Schema.voices.Add("Human", "NOO2", "No! Nooo!.", {"vo/coast/odessa/male01/nlo_cubdeath02.wav", "vo/coast/odessa/female01/nlo_cubdeath02.wav"})
Schema.voices.Add("Human", "NO ARGUMENT", "No argument there.", {"vo/npc/male01/answer33.wav", "vo/npc/female01/answer33.wav"})
Schema.voices.Add("Human", "NO KIDS", "I'm glad there's no kids around to see this.", {"vo/npc/male01/question30.wav", "vo/npc/female01/question30.wav"})
Schema.voices.Add("Human", "NOT GOING TO TELL", "I'm not even going to tell you what that reminds me of.", {"vo/npc/male01/question14.wav", "vo/npc/female01/question14.wav"})
Schema.voices.Add("Human", "NOT OUT HERE", "I can't be seen talking to you, not out here.", {"vo/trainyard/male01/cit_bench02.wav", "vo/trainyard/female01/cit_bench02.wav"})
Schema.voices.Add("Human", "NOT SURE", "I'm not sure how to take that.", {"vo/npc/male01/vanswer03.wav", "vo/npc/female01/vanswer03.wav"})
Schema.voices.Add("Human", "NOT THE MAN I THOUGHT", "You're not the man I thought you were!", {"vo/npc/male01/notthemanithought01.wav", "vo/npc/female01/notthemanithought01.wav"})
Schema.voices.Add("Human", "NOW ITS PERSONAL", "Alright... now it's personal!", {"vo/outland_12/reb1_buildingexplo03.wav", "common/null.wav"})
Schema.voices.Add("Human", "NOW WHAT", "Now what?", {"vo/npc/male01/gordead_ans01.wav", "vo/npc/female01/gordead_ans01.wav"})
Schema.voices.Add("Human", "OH GOD", "Oh god!", {"vo/npc/male01/gordead_ans04.wav", "vo/npc/female01/gordead_ans04.wav"})
Schema.voices.Add("Human", "OH GOD IM NEXT", "Oh god, I'm next. I just know it!", {"vo/episode_1/npc/male01/cit_buddykilled02.wav", "vo/episode_1/npc/female01/cit_buddykilled02.wav"})
Schema.voices.Add("Human", "OH SHIT", "Oh shit!", {"vo/episode_1/npc/male01/cit_buddykilled07.wav", "vo/episode_1/npc/female01/cit_buddykilled07.wav"})
Schema.voices.Add("Human", "OH NO", "Oh no.", {"vo/npc/male01/gordead_ans05.wav", "vo/npc/female01/gordead_ans05.wav"})
Schema.voices.Add("Human", "OH BOY HERE WE GO", "Oh boy, here we go!", {"vo/outland_12/reb1_prepare_battle_01.wav", "common/null.wav"})
Schema.voices.Add("Human", "OKAY", "Okay!", {"vo/npc/male01/ok01.wav", "vo/npc/female01/ok01.wav"})
Schema.voices.Add("Human", "ONE OF THOSE DAYS", "I just knew it was going to be one of those days.", {"vo/npc/male01/question25.wav", "vo/npc/female01/question25.wav"})
Schema.voices.Add("Human", "ONE WAY", "That's... one way of looking at it.", {"vo/npc/male01/answer15.wav", "vo/npc/female01/answer15.wav"})
Schema.voices.Add("Human", "ORIGINAL THOUGHT", "Have you ever had an original thought?", {"vo/npc/male01/answer16.wav", "vo/npc/female01/answer16.wav"})
Schema.voices.Add("Human", "OUT OF YOUR WAY", "Lemme get out of your way.", {"vo/npc/male01/outofyourway02.wav", "vo/npc/female01/outofyourway02.wav"})
Schema.voices.Add("Human", "OVER HERE", "Over here!", {"vo/npc/male01/overhere01.wav", "vo/npc/female01/overhere01.wav"})
Schema.voices.Add("Human", "OVER THERE", "Over there!", {"vo/npc/male01/overthere01.wav", "vo/npc/female01/overthere01.wav"})
Schema.voices.Add("Human", "OPEN GATE", "Open the gate!", {"vo/streetwar/barricade/male01/c17_05_opengate.wav", "vo/streetwar/barricade/female01/c17_05_opengate.wav"})
Schema.voices.Add("Human", "OPEN DOOR", "Hey it's me, open the door.", {"vo/streetwar/tunnel/male01/c17_06_password01.wav", "vo/streetwar/tunnel/female01/c17_06_password01.wav"})
Schema.voices.Add("Human", "OWN MEDICINE", "How do you like a taste of your own medicine?", {"vo/outland_08/chopper/rebc_chop_hit04.wav", "common/null.wav"})
Schema.voices.Add("Human", "PAIN1", "Ow!", {"vo/npc/male01/ow01.wav", "vo/npc/female01/ow01.wav"})
Schema.voices.Add("Human", "PAIN10", "Agh!", {"vo/npc/male01/pain09.wav", "vo/npc/female01/pain09.wav"})
Schema.voices.Add("Human", "PAIN2", "Ugh!", {"vo/npc/male01/pain01.wav", "vo/npc/female01/pain01.wav"})
Schema.voices.Add("Human", "PAIN3", "Ugh!", {"vo/npc/male01/pain02.wav", "vo/npc/female01/pain02.wav"})
Schema.voices.Add("Human", "PAIN4", "Agh!", {"vo/npc/male01/pain03.wav", "vo/npc/female01/pain03.wav"})
Schema.voices.Add("Human", "PAIN5", "Ugh!", {"vo/npc/male01/pain04.wav", "vo/npc/female01/pain04.wav"})
Schema.voices.Add("Human", "PAIN6", "Hugh!", {"vo/npc/male01/pain05.wav", "vo/npc/female01/pain05.wav"})
Schema.voices.Add("Human", "PAIN7", "Augh!", {"vo/npc/male01/pain06.wav", "vo/npc/female01/pain06.wav"})
Schema.voices.Add("Human", "PAIN8", "Ugh!", {"vo/npc/male01/pain07.wav", "vo/npc/female01/pain07.wav"})
Schema.voices.Add("Human", "PAIN9", "Ugh!", {"vo/npc/male01/pain08.wav", "vo/npc/female01/pain08.wav"})
Schema.voices.Add("Human", "PARDON ME", "Pardon me.", {"vo/npc/male01/pardonme01.wav", "vo/npc/female01/pardonme01.wav"})
Schema.voices.Add("Human", "PERSONALLY", "Should I take that personally?", {"vo/npc/male01/vanswer04.wav", "vo/npc/female01/vanswer04.wav"})
Schema.voices.Add("Human", "PLEASE NO", "Please no.", {"vo/npc/male01/gordead_ans06.wav", "vo/npc/female01/gordead_ans06.wav"})
Schema.voices.Add("Human", "PORTAL", "Next portal I see, I'm jumpin' through it. Anywhere's gotta be better than this", {"vo/outland_11a/silo/reb1_idles06.wav", "common/null.wav"})
Schema.voices.Add("Human", "PUT UP WITH YOU", "That's why we put up with you.", {"vo/npc/male01/vanswer07.wav", "vo/npc/female01/vanswer07.wav"})
Schema.voices.Add("Human", "READY WHEN YOU ARE", "Ready when you are!", {"vo/npc/male01/readywhenyouare01.wav", "vo/npc/female01/readywhenyouare01.wav"})
Schema.voices.Add("Human", "RELOAD", "Cover me while I reload!", {"vo/npc/male01/coverwhilereload01.wav", "vo/npc/female01/coverwhilereload01.wav"})
Schema.voices.Add("Human", "RIGHT ON", "Right on!", {"vo/npc/male01/answer32.wav", "vo/npc/female01/answer32.wav"})
Schema.voices.Add("Human", "RUN", "Run!", {"vo/npc/male01/strider_run.wav", "vo/npc/female01/strider_run.wav"})
Schema.voices.Add("Human", "RUN2", "Run for your life!", {"vo/npc/male01/runforyourlife01.wav", "vo/npc/female01/runforyourlife01.wav"})
Schema.voices.Add("Human", "SAME HERE", "Same here.", {"vo/npc/male01/answer07.wav", "vo/npc/female01/answer07.wav"})
Schema.voices.Add("Human", "SAD NO", "No..", {"vo/episode_1/npc/male01/cit_buddykilled03.wav", "vo/episode_1/npc/female01/cit_buddykilled03.wav"})
Schema.voices.Add("Human", "SCANNERS", "Scanners!", {"vo/npc/male01/scanners01.wav", "vo/npc/female01/scanners02"})
Schema.voices.Add("Human", "SCARING THE PIDGEONS", "You're scaring off the pidgeons.", {"vo/trainyard/male01/cit_bench04.wav", "vo/trainyard/female01/cit_bench04.wav"})
Schema.voices.Add("Human", "SELL INSURANCE", "To think all I used to ever want to do was sell insurance.", {"vo/npc/male01/question02.wav", "vo/npc/female01/question02.wav"})
Schema.voices.Add("Human", "SHELLING", "They're shelling us!", {"vo/canals/male01/stn6_shellingus.wav", "vo/canals/female01/stn6_shellingus.wav"})
Schema.voices.Add("Human", "SHIT", "Shit!", {"vo/outland_12/reb1_buildingexplo06.wav", "common/null.wav"})
Schema.voices.Add("Human", "SHOWER", "I can't remember the last time I had a shower.", {"vo/npc/male01/question19.wav", "vo/npc/female01/question19.wav"})
Schema.voices.Add("Human", "SHUT UP", "Shut up.", {"vo/outland_08/chopper/reb_chop_shipdown03.wav", "common/null.wav"})
Schema.voices.Add("Human", "SHUT UP2", "I'm not even going to tell you to shut up!", {"vo/npc/male01/answer17.wav", "vo/npc/female01/answer17.wav"})
Schema.voices.Add("Human", "SO WHAT NEXT", "So what happens next?", {"vo/outland_11a/silo/reb1_idles01.wav", "common/null.wav"})
Schema.voices.Add("Human", "SO WHAT NOW", "So, what now?", {"vo/outland_11a/silo/reb1_idles01.wav", "common/null.wav"})
Schema.voices.Add("Human", "SORRY", "Sorry.", {"vo/npc/male01/sorry01.wav", "vo/npc/female01/sorry01.wav"})
Schema.voices.Add("Human", "SPEAK ENGLISH", "Speak English!", {"vo/npc/male01/vanswer05.wav", "vo/npc/female01/vanswer05.wav"})
Schema.voices.Add("Human", "SPREAD THE WORD", "Spread the word.", {"vo/npc/male01/gordead_ans10.wav", "vo/npc/female01/gordead_ans10.wav"})
Schema.voices.Add("Human", "STAY HERE", "I'll stay here.", {"vo/npc/male01/illstayhere01.wav", "vo/npc/female01/illstayhere01.wav"})
Schema.voices.Add("Human", "STICKING HERE", "I'm sticking here.", {"vo/npc/male01/imstickinghere01.wav", "vo/npc/female01/imstickinghere01.wav"})
Schema.voices.Add("Human", "STINKING BUGS", "Stinkin' bugs!", {"vo/outland_02/griggs_killlion_04.wav", "common/null.wav"})
Schema.voices.Add("Human", "STAND BACK IT'S GONNA BLOW", "Stand back! It's gonna blow!", {"vo/streetwar/tunnel/male01/c17_06_det04.wav", "vo/streetwar/tunnel/male01/c17_06_det04.wav"})
Schema.voices.Add("Human", "STOP LOOKING", "Stop looking at me like that.", {"vo/npc/male01/vquestion01.wav", "vo/npc/female01/vquestion01.wav"})
Schema.voices.Add("Human", "STRAIGHT TO THEIR UNIVERSE", "Let's take the fight to the Combine, eh doc? Straight to their universe, whaddya say?", {"vo/outland_11a/silo/reb1_idles07.wav", "common/null.wav"})
Schema.voices.Add("Human", "STRIDER", "Strider!", {"vo/npc/male01/strider.wav", "vo/npc/female01/strider.wav"})
Schema.voices.Add("Human", "SUPPLIES", "Hey down there! Supplies!", {"vo/npc/male01/cit_dropper01.wav", "vo/npc/female01/cit_dropper01.wav"})
Schema.voices.Add("Human", "SURE ABOUT THAT", "You sure about that?", {"vo/npc/male01/answer37.wav", "vo/npc/female01/answer37.wav"})
Schema.voices.Add("Human", "TAKE A MIRACLE", "It's gonna take a damn miracle to get us out of this!", {"vo/outland_12/reb1_lastwaveannounced06.wav", "common/null.wav"})
Schema.voices.Add("Human", "TAKE COVER", "Take cover!", {"vo/npc/male01/takecover02.wav", "vo/npc/female01/takecover02.wav"})
Schema.voices.Add("Human", "TAKE IT DOWN", "God damn it, take it down!", {"vo/outland_12/reb1_sawmillexplo06.wav", "common/null.wav"})
Schema.voices.Add("Human", "TAKE MEDKIT", "Take this medkit.", {"vo/npc/male01/health03.wav", "vo/npc/female01/headsup02.wav"})
Schema.voices.Add("Human", "TALK ABOUT IT LATER", "Can't we talk about this later?", {"vo/npc/male01/answer05.wav", "vo/npc/female01/answer05.wav"})
Schema.voices.Add("Human", "TALKING TO YOURSELF", "You're talking to yourself again.", {"vo/npc/male01/answer09.wav", "vo/npc/female01/answer09.wav"})
Schema.voices.Add("Human", "THE POINT", "What's the point?!", {"vo/npc/male01/gordead_ans12.wav", "vo/npc/female01/gordead_ans12.wav"})
Schema.voices.Add("Human", "THE USE", "What's the use?", {"vo/npc/male01/gordead_ans11.wav", "vo/npc/female01/gordead_ans11.wav"})
Schema.voices.Add("Human", "THINKING ABOUT", "Doesn't bare thinking about.", {"vo/npc/male01/answer12.wav", "vo/npc/female01/answer12.wav"})
Schema.voices.Add("Human", "THIS CAN'T BE", "This can't be!", {"vo/npc/male01/gordead_ques06.wav", "vo/npc/female01/gordead_ques06.wav"})
Schema.voices.Add("Human", "THIS IS BAD", "This is bad!", {"vo/npc/male01/gordead_ques10.wav", "vo/npc/female01/gordead_ques10.wav"})
Schema.voices.Add("Human", "THIS WAR", "I don't think this war is ever gonna end.", {"vo/npc/male01/question01.wav", "vo/npc/female01/question01.wav"})
Schema.voices.Add("Human", "THIS WAY", "This way.", {"vvo/coast/odessa/male01/stairman_follow01.wav", "vo/coast/odessa/female01/stairman_follow01.wav"})
Schema.voices.Add("Human", "THOUGHT ANGRY", "We thought you were here to help!", {"vo/npc/male01/heretohelp01.wav", "vo/npc/female01/heretohelp01.wav"})
Schema.voices.Add("Human", "THOUGHT SAD", "We thought you were here to help!", {"vo/npc/male01/heretohelp02.wav", "vo/npc/female01/heretohelp02.wav"})
Schema.voices.Add("Human", "TOMBSTONE", "I'll put it on your tombstone.", {"vo/npc/male01/answer11.wav", "vo/npc/female01/answer11.wav"})
Schema.voices.Add("Human", "TOO LOUD", "I wouldn't say that too loud...", {"vo/npc/male01/answer10.wav", "vo/npc/female01/answer10.wav"})
Schema.voices.Add("Human", "TRUSTED", "We trusted you!", {"vo/npc/male01/wetrustedyou02.wav", "vo/npc/female01/wetrustedyou02.wav"})
Schema.voices.Add("Human", "TUNE", "I can't get this tune out of my head... *Whistling*", {"vo/npc/male01/question23.wav", "vo/npc/female01/question23.wav"})
Schema.voices.Add("Human", "UNWANTED ATTENTION", "Stay back, you'll attract unwanted attention.", {"vo/trainyard/male01/cit_bench01.wav", "vo/trainyard/female01/cit_bench01.wav"})
Schema.voices.Add("Human", "USE A DRINK", "Well... I could sure use a drink. Who's with me?", {"vo/outland_08/chopper/reb_chop_useadrink02.wav", "common/null.wav"})
Schema.voices.Add("Human", "UH OH", "Uh oh!", {"vo/npc/male01/uhoh.wav", "vo/npc/female01/uhoh.wav"})
Schema.voices.Add("Human", "VORTS CALLING", "The Vorts are calling ya!", {"vo/outland_02/griggs_vortscalling.wav", "common/null.wav"})
Schema.voices.Add("Human", "VORTS PISSED", "Jeez... I've never seen the Vorts this pissed!", {"vo/outland_02/griggs_watchvorts_04.wav", "common/null.wav"})
Schema.voices.Add("Human", "VORTS WOULD SAY", "Uh, I dunno. Sounds like somethin' the Vorts would say.", {"vo/outland_02/griggs_vortswouldsay.wav", "common/null.wav"})
Schema.voices.Add("Human", "WAIT IN LINE", "You gotta be damn hungry to wait in line for this crap.", {"vo/trainyard/male01/cit_foodline03.wav", "vo/trainyard/female01/cit_foodline03.wav"})
Schema.voices.Add("Human", "WANDERING AROUND", "This is no time to be wandering around! The Combine's closing in!", {"vo/coast/odessa/male01/nlo_citizen_greet03.wav", "vo/coast/odessa/female01/nlo_citizen_greet03.wav"})
Schema.voices.Add("Human", "WAITING FOR SOMEBODY", "You waiting for somebody?", {"vo/npc/male01/waitingsomebody.wav", "vo/npc/female01/waitingsomebody.wav"})
Schema.voices.Add("Human", "WANNA BET", "Wanna bet?", {"vo/npc/male01/answer27.wav", "vo/npc/female01/answer27.wav"})
Schema.voices.Add("Human", "WASN'T PART OF THE PLAN", "I'm pretty sure this wasn't part of the plan.", {"vo/npc/male01/question11.wav", "vo/npc/female01/question11.wav"})
Schema.voices.Add("Human", "WATCH OUT", "Watch out!", {"vo/npc/male01/watchout.wav", "vo/npc/female01/watchout.wav"})
Schema.voices.Add("Human", "WE CAN DO THIS", "We can do this, right guys? ...yeah, we can do this...", {"vo/outland_02/griggs_betweenwave_09.wav", "common/null.wav"})
Schema.voices.Add("Human", "WE NEED TO STOP THEM HERE", "We need to stop them here!", {"vo/outland_12/reb1_prepare_battle_03.wav", "common/null.wav"})
Schema.voices.Add("Human", "WELL NOW WHAT", "Well... now what?", {"vo/npc/male01/gordead_ans15.wav", "vo/npc/female01/gordead_ans15.wav"})
Schema.voices.Add("Human", "WHAT AM I SUPPOSED TO DO ABOUT IT", "What am I suppose to do about it?", {"vo/npc/male01/answer29.wav", "vo/npc/male01/feanswer29.wav"})
Schema.voices.Add("Human", "WHAT A WAY TO GO", "What a way to go.", {"vo/npc/male01/gordead_ques02.wav", "vo/npc/female01/gordead_ques02.wav"})
Schema.voices.Add("Human", "WHAT I THINK", "Doesn't anyone care what I think?", {"vo/npc/male01/question22.wav", "vo/npc/female01/question22.wav"})
Schema.voices.Add("Human", "WHAT YOU'RE DOING", "Watch what you're doing!", {"vo/npc/male01/watchwhat.wav", "vo/npc/female01/watchwhat"})
Schema.voices.Add("Human", "WHO AM I KIDDING", "When this is all over... Who am I kidding..", {"vo/npc/male01/question04.wav", "vo/npc/female01/question04.wav"})
Schema.voices.Add("Human", "WHOOPS", "Whoops!", {"vo/npc/male01/whoops01.wav", "vo/npc/female01/whoops01.wav"})
Schema.voices.Add("Human", "WHY ARE YOU TELLING ME", "Why are you telling me?", {"vo/npc/male01/answer24.wav", "vo/npc/female01/answer24.wav"})
Schema.voices.Add("Human", "WHY GO ON", "Why go on?", {"vo/npc/male01/gordead_ans13.wav", "vo/npc/female01/gordead_ans13.wav"})
Schema.voices.Add("Human", "WHY SO MANY", "Why are there so many?", {"vo/outland_02/griggs_whysomany.wav", "common/null.wav"})
Schema.voices.Add("Human", "WISH I HAD A DIME", "I wish I had a dime for every time somebody said that.", {"vo/npc/male01/answer28.wav", "vo/npc/female01/answer28.wav"})
Schema.voices.Add("Human", "WITH YOU", "I'm with you.", {"vo/npc/male01/answer13.wav", "vo/npc/female01/answer13.wav"})
Schema.voices.Add("Human", "WORD TO THE WISE", "Word to the wise, keep it to yourself.", {"vo/trainyard/male01/cit_pedestrian02.wav", "vo/trainyard/female01/cit_pedestrian02.wav"})
Schema.voices.Add("Human", "WORSE NOT BETTER", "Looks to me like things are getting worse, not better!", {"vo/npc/male01/question12.wav", "vo/npc/female01/question12.wav"})
Schema.voices.Add("Human", "YEAH", "Yeah!", {"vo/npc/male01/yeah02.wav", "vo/npc/female01/yeah02.wav"})
Schema.voices.Add("Human", "YOU OKAY?!", "You okay?!", {"vo/episode_1/npc/male01/cit_buddykilled01.wav", "vo/episode_1/npc/female01/cit_buddykilled01.wav"})
Schema.voices.Add("Human", "YOU ALL OVER", "That's you all over.", {"vo/npc/male01/answer01.wav", "vo/npc/female01/answer01.wav"})
Schema.voices.Add("Human", "YOU MADE IT", "You made it!", {"vo/coast/barn/male01/youmadeit.wav", "vo/coast/barn/female01/youmadeit.wav"})
Schema.voices.Add("Human", "YOU AND ME BOTH", "Hah, you and me both.", {"vo/npc/male01/answer14.wav", "vo/npc/female01/answer14.wav"})
Schema.voices.Add("Human", "YOU NEVER KNOW", "You never know.", {"vo/npc/male01/answer22.wav", "vo/npc/female01/answer22.wav"})
Schema.voices.Add("Human", "YOU TALKING TO ME", "You talking to me?", {"vo/npc/male01/answer30.wav", "vo/npc/female01/answer30.wav"})
Schema.voices.Add("Human", "ZOMBIES", "Zombies!", {"vo/npc/male01/zombies02.wav", "vo/npc/female01/zombies02.wav"})
Schema.voices.Add("Human", "ZOMBIES2", "Zombies!", {"vo/npc/male01/zombies01.wav", "vo/npc/female01/zombies01.wav"})

Schema.voices.AddClass("Human", function(client)
	local char = client:GetCharacter()
	local faction = char:GetFaction()
	if faction == FACTION_CITIZEN or (faction == FACTION_MPF and !char:GetData('CombineMask', true)) then
		return true
	else
		return false
	end
end)